In [7]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a[1,5]

13

In [13]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
a[0, 1:6:2]

array([2, 4, 6])

In [18]:
a[1,5] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12  5 14]]


In [23]:
a[:,2] = [22,33]
print(a)

[[ 1  2 22  4  5  6  7]
 [ 8  9 33 11 12  5 14]]


In [25]:
b = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
b.shape

(2, 2, 2)

In [30]:
b[0,1,1]

4

In [33]:
b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
