In [3]:
import numpy as np

np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones((2,3), dtype="int32")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [7]:
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [9]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [10]:
np.random.rand(4,2)

array([[0.61894228, 0.65888938],
       [0.72301685, 0.60267259],
       [0.29826727, 0.35981712],
       [0.97227326, 0.0415789 ]])

In [15]:
np.random.randint(4,7, size=(3,4))

array([[5, 5, 5, 6],
       [4, 5, 4, 4],
       [5, 6, 6, 4]])

In [19]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [46]:
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])