In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [4]:
a * 2

array([2, 4, 6, 8])

In [6]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.min(stats, axis=1)

array([1, 4])

In [11]:
np.sum(stats, axis=1)

array([ 6, 15])

In [13]:
before = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
after = before.reshape(4, 2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [20]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack((h1, h2))

array([1, 2, 3, 4, 5, 6, 7, 8])