In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
a.ndim

1

In [14]:
b.shape

(2, 3)

In [30]:
b.dtype

dtype('float64')

In [9]:
a.itemsize

4

In [10]:
a.size

3

In [11]:
a.nbytes

12